# Generated by Django 5.0.7 on 2024-07-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movieTitle', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('reviewContent', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
                ('reviewer_email_id', models.EmailField(max_length=254)),
                ('genres', models.CharField(max_length=200)),
            ],
        ),
    ]
