# Generated by Django 5.0.7 on 2024-07-31 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='createdAt',
        ),
    ]
